# Simple canary: two deployments and a service; traffic split simulated by adjusting service selector manually
apiVersion: v1
kind: Service
metadata:
  name: canary-svc
spec:
  selector:
    app: blue
  ports:
  - port: 80
    targetPort: 5678
